import type { StudioInfo, Service, Photography } from '@/types/photography';

export const studioInfo: StudioInfo = {
  name: 'Precious One Photography',
  tagline: 'Timeless Memories of Your Most Precious Moments',
  description:
    'Welcome to Precious One Photography, an Abu Dhabi-based photography studio specialising in baby and family photography.',
  speciality:
    'We have a special love for newborn photography. Those first few days are incredibly precious and pass by so quickly. We focus on capturing your baby\'s tiny details, beautiful expressions, and those once-in-a-lifetime moments in a timeless and artistic way. Every session is thoughtfully planned with care, patience, and attention to detail to ensure a comfortable experience for both baby and family.',
  privacy:
    'Your comfort, privacy, and security are extremely important to us. To provide a comfortable experience that respects local culture and family privacy, the entire process at Precious One Photography—including photography, editing, and printing—is handled exclusively by women. We are committed to creating a welcoming and private environment where families can feel completely comfortable throughout their photography experience.',
  phone: '+971 50 123 4567',
  whatsapp: '+971 50 123 4567',
  email: 'hello@preciousonephotography.com',
  address: 'Abu Dhabi, United Arab Emirates',
  openingHours: 'Sunday - Saturday: 9:00 AM - 6:00 PM',
  instagram: 'https://www.instagram.com/preciousonephotography',
  bookingMethod: 'whatsapp',
};

export const services: Service[] = [
  {
    id: 'newborn',
    title: 'Newborn Photography',
    shortTitle: 'Newborn',
    description:
      'Capturing the delicate details and fleeting moments of your baby\'s first days with timeless artistry.',
    category: 'newborn',
    imageUrl: '/images/portfolio/photo-2.jpeg',
    gallery: [
      '/images/portfolio/photo-2.jpeg',
      '/images/portfolio/photo-5.jpeg',
      '/images/portfolio/photo-1.jpeg',
      '/images/portfolio/photo-3.jpeg',
    ],
    longDescription:
      'The first few weeks of your baby\'s life are fleeting — a window of tiny fingers, soft curls, and peaceful slumber that closes all too quickly. Our newborn sessions are thoughtfully paced around your baby\'s needs, with gentle handling, warm studio conditions, and plenty of time for feeding and settling. We use soft, natural light and hand-picked props to create heirloom portraits that capture the wonder of those very first days — timeless images you will treasure for a lifetime.',
    idealFor: 'Babies between 5–14 days old, in the comfort of our warm Abu Dhabi studio.',
    packages: [
      {
        name: 'Essential',
        price: 'AED 1,200',
        features: ['2-hour studio session', '15 edited digital images', '1 outfit & prop setup', 'Online gallery'],
      },
      {
        name: 'Signature',
        price: 'AED 1,800',
        priceNote: 'Most popular',
        popular: true,
        features: ['3-hour studio session', '30 edited digital images', '3 outfit & prop setups', 'Family inclusion', 'Fine-art retouching'],
      },
      {
        name: 'Complete',
        price: 'AED 2,500',
        features: ['4-hour studio session', '45 edited digital images', 'Unlimited setups & props', 'Family & sibling shots', '10×8 fine-art print', 'Leather keepsake album'],
      },
    ],
  },
  {
    id: 'baby-milestone',
    title: 'Baby Milestone Photography',
    shortTitle: 'Milestone',
    description:
      'Celebrating every precious milestone from first smiles to first steps.',
    category: 'baby-milestone',
    imageUrl: '/images/portfolio/photo-4.jpeg',
    gallery: [
      '/images/portfolio/photo-4.jpeg',
      '/images/portfolio/photo-7.jpeg',
      '/images/portfolio/photo-11.jpeg',
    ],
    longDescription:
      'From the first gummy smile to sitting, crawling, and those wobbly first steps — each milestone is a chapter worth preserving. Our milestone sessions are relaxed and playful, letting your little one\'s personality shine through. We build a session around their current stage, using natural prompts and soft styling to create joyful portraits that grow with your family. Whether it\'s a 6-month, 9-month, or first-birthday session, we\'ll make it effortless and fun.',
    idealFor: 'Babies aged 4–12 months, celebrating each new stage of development.',
    packages: [
      {
        name: 'Essential',
        price: 'AED 900',
        features: ['1.5-hour studio session', '12 edited digital images', '1 outfit setup', 'Online gallery'],
      },
      {
        name: 'Signature',
        price: 'AED 1,400',
        priceNote: 'Most popular',
        popular: true,
        features: ['2.5-hour studio session', '25 edited digital images', '3 outfit setups', 'Family inclusion', 'Fine-art retouching'],
      },
      {
        name: 'Complete',
        price: 'AED 1,900',
        features: ['3-hour studio session', '35 edited digital images', 'Unlimited setups & props', 'Family & sibling shots', 'Fine-art print', 'Keepsake album'],
      },
    ],
  },
  {
    id: 'cake-smash',
    title: 'Cake Smash Photography',
    shortTitle: 'Cake Smash',
    description:
      'Joyful and playful sessions celebrating your little one\'s first birthday.',
    category: 'cake-smash',
    imageUrl: '/images/portfolio/photo-10.jpeg',
    gallery: [
      '/images/portfolio/photo-10.jpeg',
      '/images/portfolio/photo-8.jpeg',
      '/images/portfolio/photo-14.jpeg',
    ],
    longDescription:
      'One year, one very excited little one, and one glorious, icing-covered celebration. Our cake smash sessions are all about letting go of the "perfect" and embracing the joyful mess. We design a whimsical set around your child\'s favourite colours and characters, provide a smash cake, and capture every giggle, squish, and frosting-covered moment. A bubble bath or mini clean-up set is included to finish the story with adorable after-shots.',
    idealFor: 'First-birthday babies ready to make a delicious, adorable mess.',
    packages: [
      {
        name: 'Essential',
        price: 'AED 1,100',
        features: ['2-hour studio session', '15 edited digital images', '1 themed set & smash cake', 'Online gallery'],
      },
      {
        name: 'Signature',
        price: 'AED 1,600',
        priceNote: 'Most popular',
        popular: true,
        features: ['2.5-hour studio session', '30 edited digital images', '2 themed sets', 'Smash cake + bubble bath', 'Family inclusion'],
      },
      {
        name: 'Complete',
        price: 'AED 2,100',
        features: ['3-hour studio session', '45 edited digital images', 'Unlimited set changes', 'Smash + bath + cake shots', 'Fine-art print', 'Keepsake album'],
      },
    ],
  },
  {
    id: 'pre-birthday',
    title: 'Pre-Birthday Photography',
    shortTitle: 'Pre-Birthday',
    description:
      'Anticipation and excitement captured before the big celebration.',
    category: 'pre-birthday',
    imageUrl: '/images/portfolio/photo-8.jpeg',
    gallery: [
      '/images/portfolio/photo-8.jpeg',
      '/images/portfolio/photo-12.jpeg',
      '/images/portfolio/photo-15.jpeg',
    ],
    longDescription:
      'The days leading up to a first birthday are filled with anticipation — the party preparations, the balloons, the excitement building in little eyes. Our pre-birthday sessions capture that beautiful in-between moment: your child at eleven-and-a-half months, standing at the edge of their first year. We use soft styling and gentle prompts to create heartfelt portraits that sit beautifully alongside your cake smash and celebration images.',
    idealFor: 'Babies aged 11–12 months, in the sweet anticipation before their first birthday.',
    packages: [
      {
        name: 'Essential',
        price: 'AED 850',
        features: ['1.5-hour studio session', '12 edited digital images', '1 outfit setup', 'Online gallery'],
      },
      {
        name: 'Signature',
        price: 'AED 1,300',
        priceNote: 'Most popular',
        popular: true,
        features: ['2-hour studio session', '25 edited digital images', '3 outfit setups', 'Family inclusion'],
      },
      {
        name: 'Complete',
        price: 'AED 1,750',
        features: ['2.5-hour studio session', '35 edited digital images', 'Unlimited setups', 'Fine-art print', 'Keepsake album'],
      },
    ],
  },
  {
    id: 'family',
    title: 'Family Sessions',
    shortTitle: 'Family',
    description:
      'Beautiful portraits that celebrate the love shared between family members.',
    category: 'family',
    imageUrl: '/images/portfolio/WhatsApp Image 2026-09-01 at 5.42.12 PM (1).jpeg',
    gallery: [
      '/images/portfolio/WhatsApp Image 2026-09-01 at 5.42.12 PM (1).jpeg',
      '/images/portfolio/WhatsApp Image 2026-09-01 at 5.42.11 PM (1).jpeg',
      '/images/portfolio/WhatsApp Image 2026-09-01 at 5.42.13 PM (1).jpeg',
    ],
    longDescription:
      'Some of the most precious photographs a family will ever own are the ones taken together. Our family sessions are relaxed and unhurried, capturing genuine connection, laughter, and the quiet in-between moments that make your family yours. We guide you naturally through poses and playful prompts so everyone — from grandparents to the littlest ones — feels at ease. The result is a collection of warm, candid portraits you\'ll want on every wall.',
    idealFor: 'Growing families, from new parents to multi-generational gatherings.',
    packages: [
      {
        name: 'Essential',
        price: 'AED 1,000',
        features: ['1.5-hour session', '15 edited digital images', 'Outdoor or studio', 'Online gallery'],
      },
      {
        name: 'Signature',
        price: 'AED 1,500',
        priceNote: 'Most popular',
        popular: true,
        features: ['2-hour session', '30 edited digital images', '2 locations', 'Up to 5 family members', 'Fine-art retouching'],
      },
      {
        name: 'Complete',
        price: 'AED 2,000',
        features: ['2.5-hour session', '45 edited digital images', 'Unlimited family members', 'Multiple locations', 'Fine-art print', 'Keepsake album'],
      },
    ],
  },
  {
    id: 'maternity',
    title: 'Maternity Photography',
    shortTitle: 'Maternity',
    description:
      'Elegantly documenting the beautiful journey of motherhood.',
    category: 'maternity',
    imageUrl: '/images/portfolio/photo-6.jpeg',
    gallery: [
      '/images/portfolio/photo-6.jpeg',
      '/images/portfolio/photo-9.jpeg',
      '/images/portfolio/photo-13.jpeg',
    ],
    longDescription:
      'Pregnancy is one of the most fleeting and beautiful chapters of a woman\'s life. Our maternity sessions honour this journey with elegant, soft-light portraiture that celebrates your changing body and the life growing within. We offer a curated wardrobe of flowing gowns and draping fabrics, and every session is handled with complete discretion and care by our all-women team. The result is a timeless collection that captures the quiet anticipation of the life about to begin.',
    idealFor: 'Mothers-to-be between 28–36 weeks, at the height of their glow.',
    packages: [
      {
        name: 'Essential',
        price: 'AED 1,100',
        features: ['1.5-hour studio session', '15 edited digital images', 'Gown & fabric wardrobe', 'Online gallery'],
      },
      {
        name: 'Signature',
        price: 'AED 1,600',
        priceNote: 'Most popular',
        popular: true,
        features: ['2-hour studio session', '30 edited digital images', 'Partner inclusion', '3 outfit changes', 'Fine-art retouching'],
      },
      {
        name: 'Complete',
        price: 'AED 2,200',
        features: ['2.5-hour studio session', '45 edited digital images', 'Unlimited outfit changes', 'Partner & sibling shots', 'Fine-art print', 'Keepsake album'],
      },
    ],
  },
];

export const portfolio: Photography[] = [
  {
    id: 'newborn-1',
    title: 'Tiny Details',
    category: 'newborn',
    imageUrl: '/images/portfolio/photo-1.jpeg',
    description: 'Beautiful newborn photography capturing tiny details',
    order: 1,
    featured: true,
  },
  {
    id: 'newborn-2',
    title: 'Peaceful Dreams',
    category: 'newborn',
    imageUrl: '/images/portfolio/photo-2.jpeg',
    description: 'Serene newborn portrait with delicate headband',
    order: 2,
    featured: true,
  },
  {
    id: 'newborn-3',
    title: 'Sweet Slumber',
    category: 'newborn',
    imageUrl: '/images/portfolio/photo-3.jpeg',
    description: 'Peaceful sleeping newborn on soft pink backdrop',
    order: 3,
    featured: true,
  },
  {
    id: 'newborn-4',
    title: 'Little Explorer',
    category: 'newborn',
    imageUrl: '/images/portfolio/photo-4.jpeg',
    description: 'Adorable newborn on swing with teddy bear',
    order: 4,
    featured: true,
  },
  {
    id: 'newborn-5',
    title: 'Wrapped in Love',
    category: 'newborn',
    imageUrl: '/images/portfolio/photo-5.jpeg',
    description: 'Swaddled newborn in warm embrace',
    order: 5,
    featured: false,
  },
  {
    id: 'newborn-6',
    title: 'First Moments',
    category: 'newborn',
    imageUrl: '/images/portfolio/photo-6.jpeg',
    description: 'Capturing the very first moments of life',
    order: 6,
    featured: false,
  },
  {
    id: 'newborn-7',
    title: 'Gentle Touch',
    category: 'newborn',
    imageUrl: '/images/portfolio/photo-7.jpeg',
    description: 'Delicate newborn details captured beautifully',
    order: 7,
    featured: false,
  },
  {
    id: 'newborn-8',
    title: 'Angel Baby',
    category: 'newborn',
    imageUrl: '/images/portfolio/photo-8.jpeg',
    description: 'Angelic newborn portrait with soft lighting',
    order: 8,
    featured: false,
  },
  {
    id: 'newborn-9',
    title: 'Tiny Treasures',
    category: 'newborn',
    imageUrl: '/images/portfolio/photo-9.jpeg',
    description: 'Cherishing the tiny treasures of newborn days',
    order: 9,
    featured: false,
  },
  {
    id: 'newborn-10',
    title: 'Pure Love',
    category: 'newborn',
    imageUrl: '/images/portfolio/photo-10.jpeg',
    description: 'Pure love captured in a single frame',
    order: 10,
    featured: false,
  },
  {
    id: 'newborn-11',
    title: 'Dreamy Eyes',
    category: 'newborn',
    imageUrl: '/images/portfolio/photo-11.jpeg',
    description: 'Newborn with dreamy peaceful expression',
    order: 11,
    featured: false,
  },
  {
    id: 'newborn-12',
    title: 'Soft Embrace',
    category: 'newborn',
    imageUrl: '/images/portfolio/photo-12.jpeg',
    description: 'Newborn wrapped in soft comforting embrace',
    order: 12,
    featured: false,
  },
  {
    id: 'newborn-13',
    title: 'Little Star',
    category: 'newborn',
    imageUrl: '/images/portfolio/photo-13.jpeg',
    description: 'Our little star shining bright',
    order: 13,
    featured: false,
  },
  {
    id: 'newborn-14',
    title: 'Precious Smile',
    category: 'newborn',
    imageUrl: '/images/portfolio/photo-14.jpeg',
    description: 'A precious smile that melts hearts',
    order: 14,
    featured: false,
  },
  {
    id: 'newborn-15',
    title: 'Sweet Dreams',
    category: 'newborn',
    imageUrl: '/images/portfolio/photo-15.jpeg',
    description: 'Dreaming of a beautiful future',
    order: 15,
    featured: false,
  },
  /* ─── WhatsApp portfolio additions ─── */
  {
    id: 'wa-1',
    title: 'Little Hands',
    category: 'newborn',
    imageUrl: '/images/portfolio/WhatsApp Image 2026-09-01 at 5.42.10 PM.jpeg',
    description: 'Tiny newborn hands cradled with love',
    order: 16,
    featured: true,
  },
  {
    id: 'wa-2',
    title: 'Basket Dreams',
    category: 'newborn',
    imageUrl: '/images/portfolio/WhatsApp Image 2026-09-01 at 5.42.10 PM (1).jpeg',
    description: 'Newborn sleeping peacefully in a woven basket',
    order: 17,
    featured: true,
  },
  {
    id: 'wa-3',
    title: 'Tiny Toes',
    category: 'newborn',
    imageUrl: '/images/portfolio/WhatsApp Image 2026-09-01 at 5.42.10 PM (2).jpeg',
    description: 'Close-up of adorable tiny toes',
    order: 18,
    featured: false,
  },
  {
    id: 'wa-4',
    title: 'Wrapped in Blooms',
    category: 'newborn',
    imageUrl: '/images/portfolio/WhatsApp Image 2026-09-01 at 5.42.11 PM.jpeg',
    description: 'Newborn nestled among delicate florals',
    order: 19,
    featured: true,
  },
  {
    id: 'wa-5',
    title: "Father's Embrace",
    category: 'family',
    imageUrl: '/images/portfolio/WhatsApp Image 2026-09-01 at 5.42.11 PM (1).jpeg',
    description: 'A father tenderly holding his newborn',
    order: 20,
    featured: true,
  },
  {
    id: 'wa-6',
    title: "Parent's Love",
    category: 'family',
    imageUrl: '/images/portfolio/WhatsApp Image 2026-09-01 at 5.42.11 PM (2).jpeg',
    description: 'Parents gazing at their newborn with adoration',
    order: 21,
    featured: false,
  },
  {
    id: 'wa-7',
    title: 'Lace Dreams',
    category: 'newborn',
    imageUrl: '/images/portfolio/WhatsApp Image 2026-09-01 at 5.42.11 PM (3).jpeg',
    description: 'Newborn portrait with delicate lace details',
    order: 22,
    featured: false,
  },
  {
    id: 'wa-8',
    title: 'Teddy Bear',
    category: 'newborn',
    imageUrl: '/images/portfolio/WhatsApp Image 2026-09-01 at 5.42.12 PM.jpeg',
    description: 'Newborn cuddled with a soft teddy bear',
    order: 23,
    featured: true,
  },
  {
    id: 'wa-9',
    title: 'Complete Family',
    category: 'family',
    imageUrl: '/images/portfolio/WhatsApp Image 2026-09-01 at 5.42.12 PM (1).jpeg',
    description: 'The whole family together in one beautiful frame',
    order: 24,
    featured: true,
  },
  {
    id: 'wa-10',
    title: "Big Brother's Love",
    category: 'family',
    imageUrl: '/images/portfolio/WhatsApp Image 2026-09-01 at 5.42.12 PM (2).jpeg',
    description: 'Big brother meeting his new sibling',
    order: 25,
    featured: false,
  },
  {
    id: 'wa-11',
    title: 'Swinging Dreams',
    category: 'newborn',
    imageUrl: '/images/portfolio/WhatsApp Image 2026-09-01 at 5.42.13 PM.jpeg',
    description: 'Newborn in denim overalls on a rustic swing',
    order: 26,
    featured: true,
  },
  {
    id: 'wa-12',
    title: 'Floral Embrace',
    category: 'family',
    imageUrl: '/images/portfolio/WhatsApp Image 2026-09-01 at 5.42.13 PM (1).jpeg',
    description: 'Family portrait against a lush floral backdrop',
    order: 27,
    featured: false,
  },
  {
    id: 'wa-13',
    title: 'Purple Dreams',
    category: 'newborn',
    imageUrl: '/images/portfolio/WhatsApp Image 2026-09-01 at 5.42.13 PM (2).jpeg',
    description: 'Newborn in a ruffled purple tutu with flower headband',
    order: 28,
    featured: true,
  },
  {
    id: 'wa-14',
    title: 'Bear Cuddle',
    category: 'newborn',
    imageUrl: '/images/portfolio/WhatsApp Image 2026-09-01 at 5.42.14 PM.jpeg',
    description: 'Sleeping newborn in a fuzzy bear hood',
    order: 29,
    featured: false,
  },
  {
    id: 'wa-15',
    title: 'Snuggle Friends',
    category: 'newborn',
    imageUrl: '/images/portfolio/WhatsApp Image 2026-09-01 at 5.42.14 PM (1).jpeg',
    description: 'Newborn surrounded by soft teddy friends',
    order: 30,
    featured: true,
  },
];

export const heroMessage = 'Capturing the moments you will treasure forever.';
